### ISSUE TITLE
Executable does not run on a 2019 MacBook Pro

### ISSUE THREAD

**Issue by kluen** [kitlangton/given#1]
Hi, I installed `given` through Homebrew, as described in the README. Running it gives me this:

```
❯ given
zsh: bad CPU type in executable: given
```

This is on a 
2019 MacBook Pro with a 2,3 GHz 8-Core Intel Core i9

**Comment by kluen** [comment]
If I install it via `cargo`, it works, btw.

**Comment by kitlangton** [comment]
Doh. Yeah, I need to update the homebrew file :) 
I think the current binary is for ARM64 only. Thanks for letting me know!

**Comment by kitlangton** [comment]
I updated the formula to just install with cargo 😆 Turns out that's a relatively common approach, and it should basically just work for everyone.
